filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.kibana:
  host: "kibana:5601"

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/logs/**/logs/*.log
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
  username: "elastic"
  password: "changeme"
